### ISSUE TITLE
Missing References

### ISSUE THREAD

**Issue by Swedz** [mirraj2/EZDB#1]
When I implemented this repository into my maven project, I have all of the dependencies supplied, however I can't find where the `ox.*` packages come from. Sorry if I'm missing something, but I can't find where to reference them as a dependency.

**Comment by mirraj2** [comment]
Oh, sorry about that, need to add that to the documentation.  You an find it here:  https://github.com/mirraj2/ox

**Comment by mirraj2** [comment]
@Swedz I highly recommend you take a look at Ox, because it has a very cool/useful stuff that I use all the time in my projects.

**Comment by Swedz** [comment]
Will do! Thanks for the help.
