### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by byBackfish** [mirraj2/EZDB#6]
Hey, so when i use this like a normal Java Application, its working fine, but if i put it into my Spigot (Minecraft) Plugins, its saying

java.lang.NoSuchMethodError: com.google.common.base.CharMatcher.whitespace()Lcom/google/common/base/CharMatcher; non maven

Any Idea why?

**Comment by byBackfish** [comment]
Or a better Question, how can i get that api as a Jar? Do I have to self compile it?

**Comment by fireboyev** [comment]
It shows that error because bukkit/spigot pre 1.10 uses an older version of Google guava. It'll only work on newer versions of bukkit. The only thing I would say you could do is recompile the server jar with a newer version or use shadow jar to rename all the packages of the guava to something else

**Comment by byBackfish** [comment]
mmh okay. Thanks

**Comment by byBackfish** [comment]
Sorry, if im asking for too much, but do you know any Documentation for that? Like i dont really know what you mean with shadow jar? Thanks

**Comment by fireboyev** [comment]
Google shadow jar package relocation gradle

**Comment by byBackfish** [comment]
Okay. I got it now, but now my last question is, where do I need to put the maven shade in? In the Api or in the Spigot Plugin? Like I made ezdb into a api for the spigot Plugin so I don't need to copy the classes in every time
